
import { Job } from '../types/job';
import { Applicant } from '../types/applicant';

export const mockApplicants: Applicant[] = [
  {
    id: 'app1',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '555-111-2222',
    resumeUrl: '/mock-docs/alice_resume.pdf',
    coverLetterUrl: '/mock-docs/alice_coverletter.pdf',
    appliedDate: '2024-07-01',
  },
  {
    id: 'app2',
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    phone: '555-333-4444',
    resumeUrl: '/mock-docs/bob_resume.pdf',
    portfolioUrl: 'http://bobwilliams.com/portfolio',
    appliedDate: '2024-07-02',
  },
  {
    id: 'app3',
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '555-555-6666',
    resumeUrl: '/mock-docs/charlie_resume.pdf',
    appliedDate: '2024-07-03',
  },
  {
    id: 'app4',
    name: 'Diana Prince',
    email: 'diana.p@example.com',
    phone: '555-777-8888',
    resumeUrl: '/mock-docs/diana_resume.pdf',
    coverLetterUrl: '/mock-docs/diana_coverletter.pdf',
    appliedDate: '2024-07-04',
  },
];

export const mockRequests: Job[] = [
  {
    id: 'job1',
    status: 'Open',
    title: 'Senior Vocational Evaluator',
    applicationDeadline: '2024-08-15',
    applicantsCount: 4,
    description: 'Seeking a highly experienced vocational evaluator to conduct comprehensive assessments and provide expert testimony.',
    requiredSkills: ['Vocational Evaluation', 'Expert Testimony', 'Report Writing'],
    experienceLevel: 'senior',
    engagementType: 'project',
    workMode: 'hybrid',
    projectScope: 'large',
    startDate: '2024-09-01',
    endDate: '2025-03-01',
    teamSize: '3-5',
    location: 'Toronto, ON',
    salaryType: 'fixed',
    salaryMin: '15000',
    currency: 'CAD',
    ndaRequired: true,
    paymentTerms: 'Net 30 days',
    contactPerson: 'Jane Doe',
    contactEmail: 'jane.doe@example.com',
    contactPhone: '555-123-4567',
    communicationMethod: 'email',
    type: 'Full-time Consulting',
    datePosted: '2024-07-01',
    deadline: '2024-08-15',
  },
  {
    id: 'job2',
    status: 'Closed',
    title: 'Junior Case Manager',
    applicationDeadline: '2024-07-30',
    applicantsCount: 0,
    description: 'Entry-level position for a case manager to assist with client coordination and administrative tasks.',
    requiredSkills: ['Case Management', 'Client Communication'],
    experienceLevel: 'entry',
    engagementType: 'ongoing',
    workMode: 'remote',
    projectScope: 'small',
    startDate: '2024-08-01',
    salaryType: 'hourly',
    salaryMin: '30',
    currency: 'CAD',
    ndaRequired: false,
    paymentTerms: 'Bi-weekly',
    contactPerson: 'John Smith',
    contactEmail: 'john.smith@example.com',
    contactPhone: '555-987-6543',
    communicationMethod: 'phone',
    type: 'Part-time Support',
    datePosted: '2024-06-15',
    deadline: '2024-07-30',
  },
  {
    id: 'job3',
    status: 'Closed',
    title: 'Ergonomic Assessment Specialist',
    applicationDeadline: '2024-08-20',
    applicantsCount: 0,
    description: 'Specialist needed to perform ergonomic assessments and recommend workplace modifications.',
    requiredSkills: ['Ergonomic Assessment', 'Report Writing'],
    experienceLevel: 'intermediate',
    engagementType: 'one-time',
    workMode: 'onsite',
    projectScope: 'medium',
    startDate: '2024-09-10',
    location: 'Vancouver, BC',
    salaryType: 'fixed',
    salaryMin: '500',
    currency: 'CAD',
    ndaRequired: false,
    paymentTerms: 'Upon completion',
    contactPerson: 'Sarah Lee',
    contactEmail: 'sarah.lee@example.com',
    contactPhone: '555-234-5678',
    communicationMethod: 'email',
    type: 'One-time Project',
    datePosted: '2024-06-20',
    deadline: '2024-08-20',
  },
  {
    id: 'job4',
    status: 'Hiring',
    title: 'Medical Expert Witness',
    applicationDeadline: '2024-09-01',
    applicantsCount: 8,
    description: 'Looking for a medical expert witness for personal injury cases.',
    requiredSkills: ['Medical Expertise', 'Expert Testimony', 'Legal Documentation'],
    experienceLevel: 'senior',
    engagementType: 'ongoing',
    workMode: 'hybrid',
    projectScope: 'large',
    startDate: '2024-09-15',
    endDate: '2025-09-15',
    teamSize: '1-2',
    location: 'Montreal, QC',
    salaryType: 'hourly',
    salaryMin: '200',
    currency: 'CAD',
    ndaRequired: true,
    paymentTerms: 'Net 15 days',
    contactPerson: 'Michael Chen',
    contactEmail: 'michael.chen@example.com',
    contactPhone: '555-345-6789',
    communicationMethod: 'email',
    type: 'Expert Witness',
    datePosted: '2024-07-10',
    deadline: '2024-09-01',
  },
  {
    id: 'job5',
    status: 'Draft',
    title: 'Workplace Safety Consultant',
    applicationDeadline: '2024-08-30',
    applicantsCount: 0,
    description: 'Safety consultant needed to review workplace policies and procedures.',
    requiredSkills: ['Safety Management', 'Risk Assessment', 'Compliance'],
    experienceLevel: 'intermediate',
    engagementType: 'project',
    workMode: 'onsite',
    projectScope: 'medium',
    startDate: '2024-09-05',
    endDate: '2024-12-05',
    teamSize: '2-3',
    location: 'Calgary, AB',
    salaryType: 'fixed',
    salaryMin: '8000',
    currency: 'CAD',
    ndaRequired: false,
    paymentTerms: 'Net 30 days',
    contactPerson: 'Lisa Wang',
    contactEmail: 'lisa.wang@example.com',
    contactPhone: '555-456-7890',
    communicationMethod: 'phone',
    type: 'Safety Consulting',
    datePosted: '2024-07-12',
    deadline: '2024-08-30',
  },
  {
    id: 'job6',
    status: 'Filled',
    title: 'Workers Compensation Specialist',
    applicationDeadline: '2024-07-15',
    applicantsCount: 12,
    description: 'Specialist to handle workers compensation claims and assessments.',
    requiredSkills: ['Workers Compensation', 'Claims Management', 'Medical Assessment'],
    experienceLevel: 'senior',
    engagementType: 'ongoing',
    workMode: 'remote',
    projectScope: 'large',
    startDate: '2024-08-01',
    teamSize: '3-5',
    salaryType: 'hourly',
    salaryMin: '65',
    currency: 'CAD',
    ndaRequired: true,
    paymentTerms: 'Bi-weekly',
    contactPerson: 'David Kim',
    contactEmail: 'david.kim@example.com',
    contactPhone: '555-567-8901',
    communicationMethod: 'email',
    type: 'Claims Management',
    datePosted: '2024-06-01',
    deadline: '2024-07-15',
  },
];
